services:
  grafana:
    image: grafana/grafana # Or grafana/grafana for open-source version
    container_name: grafana
    restart: unless-stopped
    #ports:
    #  - 3000:3000 # Maps host port 3000 to container port 3000
    volumes:
      - /home/calebh/app-data/grafana:/var/lib/grafana # For persistent storage of data and configurations
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      # HTTP
      traefik.http.routers.grafana-http.rule: Host(`grafana.tiny-apps.husovich.com`)
      traefik.http.routers.grafana-http.entrypoints: http
      traefik.http.routers.grafana-http.service: grafana
      traefik.http.routers.grafana-http.middlewares: redirect-https
      # HTTP Redirect
      traefik.http.middlewares.redirect-https.redirectScheme.scheme: https
      traefik.http.middlewares.redirect-https.redirectScheme.permanent: true
      # HTTPS
      traefik.http.routers.grafana-https.rule: Host(`grafana.tiny-apps.husovich.com`)
      traefik.http.routers.grafana-https.entrypoints: https
      traefik.http.routers.grafana-https.service: grafana
      traefik.http.routers.grafana-https.tls: true
      traefik.http.routers.grafana-https.tls.certresolver: myresolver
      # Load Balancer      
      traefik.http.services.grafana.loadbalancer.server.port: 3000
   
networks:
  traefik:
    external: true
